### ISSUE TITLE
phpstorm freezes when opening a new project or any window in phpstorrm

### ISSUE THREAD

**Issue by haosmos** [patricklx/intellij-wsl-symlinks#2]
### Description

The plugin seems to work - my phpstorm installed on windows sees packages installed in wsl using the pnpm package manager, which uses symlinks. I tried installing react.js, next.js in wsl using pnpm - it seems to work: the projects are launched.
But when opening a new project, phpstorm freezes - it does not respond to any buttons or actions. The only option left is to force shutdown phpstorm through the task manager.
Also phpstorm freezes when opening any phpstorm window.
If you disable your plugin, phpstorm does not freeze.

### Steps to Reproduce

phpstorm freezes when opening a new project.

**Expected behavior:** [What you expect to happen]

new project opens

**Actual behavior:** [What actually happens]

new project does not open - phpstorm freezes

### Versions

Build #PS-241.14494.237, built on March 27, 2024

- The version of `intellij-emberjs` (`Settings` -> `Plugins` -> `Ember.js`):

ember-experimental-js - 2023.4.0. 

https://plugins.jetbrains.com/plugin/8049-ember-js - is not supported by phpstorm 2024.1

### Additional Information

![chrome_AAKvqBmz6m](https://github.com/patricklx/intellij-wsl-symlinks/assets/30666874/9ff84809-935e-490d-bcea-e61727699d1a)

![phpstorm64_eQdbuDPZ08](https://github.com/patricklx/intellij-wsl-symlinks/assets/30666874/a9b97214-bbee-473c-9133-a08a26950bfb)

![chrome_64o3kCiM3b](https://github.com/patricklx/intellij-wsl-symlinks/assets/30666874/5f03e34b-cff9-4539-871e-929201e62c11)

![yID6QkMpAR](https://github.com/patricklx/intellij-wsl-symlinks/assets/30666874/1b547437-4d4a-4c4a-a1ae-e12dcd360fb3)

**Comment by patricklx** [comment]
Hi, this should be fixes with the 2024.1.1 release.
Also, i did copy from my other plugin emberjs , the GitHub issue template and forgot to adapt it -.-

**Comment by haosmos** [comment]
Hello! 😀

Thanks for your plugin and your work! This is such a long-awaited functionality for wsl users!

I've been testing the plugin for the last couple of days with the new version of the plugin (2024.1.1). The plugin seems to be working - however, phpstorm began to freeze again. What's interesting is that one day I was able to open new projects - phpstorm didn't crash. But today I created a project (in wsl) that does not use symbolic links and when opening the phpstorm project selection window it froze again. I forced quit phpstorm through task manager, opened phpstorm again and it froze again. After that I removed the plugin and phpstorm did not freeze when opening a new project.

![chrome_Vxj3p1Uzel](https://github.com/patricklx/intellij-wsl-symlinks/assets/30666874/48cbf311-a48a-4fea-93fc-29bb7b8bfa04)

![phpstorm64_ZcxQLlKV36](https://github.com/patricklx/intellij-wsl-symlinks/assets/30666874/96a1153e-8abe-4069-9af7-a875d8b2b0da)

After that I installed the plugin again, reloaded phpstorm and I was able to open the project and work with it. But when opening a new project, phpstorm froze again.

It turns out that I can only work with the project when the plugin is installed if I first uninstall the plugin, restart phpstorm, install the plugin again and open exactly the last project I was working with before restarting phpstorm.

I don't know, maybe it's a problem with my version of phpstorm or the way my phpstorm is configured - maybe a problem with some plugins or something else.

Do you have any ideas what this might be connected with? And maybe tell me some life hacks or tricks to somehow avoid this problem with phpstorm freezing when opening a new project?

I'm ready to help you with testing - maybe you have experimental builds of the plugin, or a beta version.

Anyway, thanks for your work and for your plugin!

**Comment by patricklx** [comment]
Hi, the latest version should fix this hopefully

**Comment by haosmos** [comment]
> Hi, the latest version should fix this hopefully

Hello! 😀

I installed the new version of the plugin and so far everything is working great!

Thank you for your plugin! It's incredible that you were able to implement symlinks support and work with them from Windows applications!
